# Pod Security Standards
apiVersion: v1
kind: Namespace
metadata:
  name: i3m-platform-secure
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
# Network Policy for i3m-platform
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: i3m-platform-network-policy
  namespace: i3m-platform
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: i3m-platform
    - namespaceSelector:
        matchLabels:
          name: monitoring
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: i3m-platform
    - namespaceSelector:
        matchLabels:
          name: monitoring
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
---
# Resource Quotas
apiVersion: v1
kind: ResourceQuota
metadata:
  name: i3m-platform-quota
  namespace: i3m-platform
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    pods: "50"
    services: "20"
---
# Limit Range
apiVersion: v1
kind: LimitRange
metadata:
  name: i3m-platform-limits
  namespace: i3m-platform
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
