apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: i3m-platform
  labels:
    app: inventory-service
    tier: erp
    component: core-business
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
        tier: erp
        component: core-business
    spec:
      containers:
      - name: inventory-service
        image: i3m-platform-inventory-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3012
          name: http
        env:
        - name: SERVER_PORT
          value: "3012"
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "i3m_user"
        - name: DB_PASSWORD
          value: "i3m_password"
        - name: DB_NAME
          value: "i3m_inventory_db"
        - name: DB_SSL_MODE
          value: "disable"
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: REDIS_URL
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3012
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 3012
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: i3m-platform
  labels:
    app: inventory-service
    tier: erp
spec:
  selector:
    app: inventory-service
  ports:
  - port: 3030
    targetPort: 3012
    protocol: TCP
    name: http
  type: ClusterIP
