apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: i3m-platform
  labels:
    app: user-service
    tier: core
    version: "1.0.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
        tier: core
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3009"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
      - name: user-service
        image: i3m-platform-user-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3009
          name: http
        env:
        - name: SERVER_PORT
          value: "3009"
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ENVIRONMENT
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres-service:5432/i3m_platform?sslmode=disable"
        - name: SPRING_DATASOURCE_USERNAME
          value: "i3m_user"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "i3m_password"
        - name: SPRING_REDIS_HOST
          value: "redis-service"
        - name: SPRING_REDIS_PORT
          value: "6379"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: JWT_SECRET
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "1500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 3009
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 3009
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
      imagePullSecrets:
      - name: registry-secret

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: i3m-platform
  labels:
    app: user-service
spec:
  selector:
    app: user-service
  ports:
  - port: 3009
    targetPort: 3009
    protocol: TCP
    name: http
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-service-hpa
  namespace: i3m-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-service
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
