apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: i3m-platform
  labels:
    app: user-service
    tier: core
    version: 1.0.0
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
        tier: core
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3009"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
      - name: user-service
        image: i3m-platform-user-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3009
          name: http
          protocol: TCP
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres-service:5432/i3m_platform?sslmode=disable"
        - name: SPRING_DATASOURCE_USERNAME
          value: "i3m_user"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "i3m_password"
        - name: SPRING_REDIS_HOST
          value: "redis-service"
        - name: SPRING_REDIS_PORT
          value: "6379"
        - name: DATABASE_URL
          value: "postgresql://i3m_user:i3m_password@postgres-service:5432/i3m_platform?sslmode=disable"
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "i3m_platform"
        - name: DB_USER
          value: "i3m_user"
        - name: DB_PASSWORD
          value: "i3m_password"
        - name: DB_SSLMODE
          value: "disable"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 3009
            scheme: HTTP
          initialDelaySeconds: 300
          periodSeconds: 60
          timeoutSeconds: 30
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 3009
            scheme: HTTP
          initialDelaySeconds: 300
          periodSeconds: 30
          timeoutSeconds: 30
          failureThreshold: 3
          successThreshold: 1
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 3009
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 30
          failureThreshold: 10
          successThreshold: 1
