global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter
  - job_name: 'node-exporter'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [__meta_kubernetes_endpoints_name]
        regex: 'node-exporter'
        action: keep

  # Kubernetes API Server
  - job_name: 'kubernetes-apiservers'
    kubernetes_sd_configs:
      - role: endpoints
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        action: keep
        regex: default;kubernetes;https

  # Kubernetes Nodes
  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
      - role: node
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics

  # Kubernetes Pods
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name

  # I3M Platform Services
  - job_name: 'i3m-core-services'
    kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
            - i3m-staging
            - i3m-production
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app]
        regex: 'i3m-(api-gateway|auth-service|user-service)'
        action: keep
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__

  - job_name: 'i3m-erp-services'
    kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
            - i3m-staging
            - i3m-production
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app]
        regex: 'i3m-(finance|hrm|inventory|procurement|ecommerce|crm)-service'
        action: keep
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
        action: keep
        regex: true

  - job_name: 'i3m-analytics-services'
    kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
            - i3m-staging
            - i3m-production
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app]
        regex: 'i3m-(ai|ml-pipeline|analytics|user-analytics)-service'
        action: keep

  - job_name: 'i3m-content-services'
    kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
            - i3m-staging
            - i3m-production
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app]
        regex: 'i3m-(content|media|metadata)-service'
        action: keep

  - job_name: 'i3m-infrastructure-services'
    kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
            - i3m-staging
            - i3m-production
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app]
        regex: 'i3m-(security|observability|cost-optimization|load-balancer|secrets-management)-service'
        action: keep

  - job_name: 'i3m-marketplace-services'
    kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
            - i3m-staging
            - i3m-production
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app]
        regex: 'i3m-(template-marketplace|installation|preview)-service'
        action: keep

  - job_name: 'i3m-shared-services'
    kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
            - i3m-staging
            - i3m-production
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app]
        regex: 'i3m-(notification|workflow|billing)-service'
        action: keep

  - job_name: 'i3m-industry-services'
    kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
            - i3m-staging
            - i3m-production
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app]
        regex: 'i3m-(healthcare|agriculture)-service'
        action: keep

  - job_name: 'i3m-integration-services'
    kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
            - i3m-staging
            - i3m-production
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app]
        regex: 'i3m-(api-documentation|integration|currency-exchange)-service'
        action: keep

  # PostgreSQL Exporter
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis Exporter
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']

  # MongoDB Exporter (if using)
  - job_name: 'mongodb-exporter'
    static_configs:
      - targets: ['mongodb-exporter:9216']

  # Blackbox Exporter for endpoint monitoring
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://api.i3m-platform.com/health
        - https://app.i3m-platform.com
        - https://admin.i3m-platform.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
