server:
  port: 3029

spring:
  application:
    name: hrm-service
  
  datasource:
    url: jdbc:postgresql://localhost:5433/i3m_platform
    username: i3m_user
    password: i3m_password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_schema: hrm
  
  data:
    redis:
      host: localhost
      port: 6380
      password: i3m_redis_password
      database: 1
      timeout: 2000ms

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.i3m.hrm: INFO
